repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: go fmt ./...
        language: system
        types: [go]

      - id: go-imports
        name: goimports
        entry: goimports -w .
        language: system
        types: [go]

      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        language: system
        types: [go]

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.57.2
    hooks:
      - id: golangci-lint
        args:
          - --timeout=5m
          - --fast

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks